# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
env:
  global:
    - TRAVIS_R_VERSION="4.1.0"
apt_packages:
  - libgsl-dev
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
