// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// EMalphadQ
SEXP EMalphadQ(SEXP x, SEXP zj, SEXP z, SEXP p);
RcppExport SEXP _LRMoECPNew_EMalphadQ(SEXP xSEXP, SEXP zjSEXP, SEXP zSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type zj(zjSEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(EMalphadQ(x, zj, z, p));
    return rcpp_result_gen;
END_RCPP
}
// EMalphadQ2
SEXP EMalphadQ2(SEXP x, SEXP z, SEXP p, SEXP q);
RcppExport SEXP _LRMoECPNew_EMalphadQ2(SEXP xSEXP, SEXP zSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< SEXP >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(EMalphadQ2(x, z, p, q));
    return rcpp_result_gen;
END_RCPP
}
// intGammaLogYObs
SEXP intGammaLogYObs(SEXP m_, SEXP theta_, SEXP lower_, SEXP upper_);
RcppExport SEXP _LRMoECPNew_intGammaLogYObs(SEXP m_SEXP, SEXP theta_SEXP, SEXP lower_SEXP, SEXP upper_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type m_(m_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_(theta_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type lower_(lower_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type upper_(upper_SEXP);
    rcpp_result_gen = Rcpp::wrap(intGammaLogYObs(m_, theta_, lower_, upper_));
    return rcpp_result_gen;
END_RCPP
}
// intGammaLogYLat
SEXP intGammaLogYLat(SEXP m_, SEXP theta_, SEXP lower_, SEXP upper_);
RcppExport SEXP _LRMoECPNew_intGammaLogYLat(SEXP m_SEXP, SEXP theta_SEXP, SEXP lower_SEXP, SEXP upper_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type m_(m_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_(theta_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type lower_(lower_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type upper_(upper_SEXP);
    rcpp_result_gen = Rcpp::wrap(intGammaLogYLat(m_, theta_, lower_, upper_));
    return rcpp_result_gen;
END_RCPP
}
// XAPlusYZB
SEXP XAPlusYZB(SEXP x, SEXP a, SEXP y, SEXP z, SEXP b);
RcppExport SEXP _LRMoECPNew_XAPlusYZB(SEXP xSEXP, SEXP aSEXP, SEXP ySEXP, SEXP zSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(XAPlusYZB(x, a, y, z, b));
    return rcpp_result_gen;
END_RCPP
}
// XColMinusY
SEXP XColMinusY(SEXP x, SEXP y);
RcppExport SEXP _LRMoECPNew_XColMinusY(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(XColMinusY(x, y));
    return rcpp_result_gen;
END_RCPP
}
// XPlusYColTimesZ
SEXP XPlusYColTimesZ(SEXP x, SEXP y, SEXP z);
RcppExport SEXP _LRMoECPNew_XPlusYColTimesZ(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(XPlusYColTimesZ(x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// XPlusYZ
SEXP XPlusYZ(SEXP x, SEXP y, SEXP z);
RcppExport SEXP _LRMoECPNew_XPlusYZ(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(XPlusYZ(x, y, z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LRMoECPNew_EMalphadQ", (DL_FUNC) &_LRMoECPNew_EMalphadQ, 4},
    {"_LRMoECPNew_EMalphadQ2", (DL_FUNC) &_LRMoECPNew_EMalphadQ2, 4},
    {"_LRMoECPNew_intGammaLogYObs", (DL_FUNC) &_LRMoECPNew_intGammaLogYObs, 4},
    {"_LRMoECPNew_intGammaLogYLat", (DL_FUNC) &_LRMoECPNew_intGammaLogYLat, 4},
    {"_LRMoECPNew_XAPlusYZB", (DL_FUNC) &_LRMoECPNew_XAPlusYZB, 5},
    {"_LRMoECPNew_XColMinusY", (DL_FUNC) &_LRMoECPNew_XColMinusY, 2},
    {"_LRMoECPNew_XPlusYColTimesZ", (DL_FUNC) &_LRMoECPNew_XPlusYColTimesZ, 3},
    {"_LRMoECPNew_XPlusYZ", (DL_FUNC) &_LRMoECPNew_XPlusYZ, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LRMoECPNew(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
