# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMalphadQ <- function(x, zj, z, p) {
    .Call(`_LRMoECPNew_EMalphadQ`, x, zj, z, p)
}

EMalphadQ2 <- function(x, z, p, q) {
    .Call(`_LRMoECPNew_EMalphadQ2`, x, z, p, q)
}

sumBinomialY <- function(n, p, lower_, upper_) {
    .Call(`_LRMoECPNew_sumBinomialY`, n, p, lower_, upper_)
}

sumBinomialYObs <- function(n_, p_, lower_, upper_) {
    .Call(`_LRMoECPNew_sumBinomialYObs`, n_, p_, lower_, upper_)
}

sumBinomialYLat <- function(n_, p_, lower_, upper_) {
    .Call(`_LRMoECPNew_sumBinomialYLat`, n_, p_, lower_, upper_)
}

intBurrLogYObs <- function(k_, c_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intBurrLogYObs`, k_, c_, lambda_, lower_, upper_)
}

intBurrLogYLat <- function(k_, c_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intBurrLogYLat`, k_, c_, lambda_, lower_, upper_)
}

intBurrPolYObs <- function(k_, c_, lambda_, cc_, ll_, lower_, upper_) {
    .Call(`_LRMoECPNew_intBurrPolYObs`, k_, c_, lambda_, cc_, ll_, lower_, upper_)
}

intBurrPolYLat <- function(k_, c_, lambda_, cc_, ll_, lower_, upper_) {
    .Call(`_LRMoECPNew_intBurrPolYLat`, k_, c_, lambda_, cc_, ll_, lower_, upper_)
}

intGammaLogYObs <- function(m_, theta_, lower_, upper_) {
    .Call(`_LRMoECPNew_intGammaLogYObs`, m_, theta_, lower_, upper_)
}

intGammaLogYLat <- function(m_, theta_, lower_, upper_) {
    .Call(`_LRMoECPNew_intGammaLogYLat`, m_, theta_, lower_, upper_)
}

intInvGaussLogYObs <- function(mu_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intInvGaussLogYObs`, mu_, lambda_, lower_, upper_)
}

intInvGaussLogYLat <- function(mu_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intInvGaussLogYLat`, mu_, lambda_, lower_, upper_)
}

intInvGaussYObs <- function(mu_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intInvGaussYObs`, mu_, lambda_, lower_, upper_)
}

intInvGaussYLat <- function(mu_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intInvGaussYLat`, mu_, lambda_, lower_, upper_)
}

intInvGaussInvYObs <- function(mu_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intInvGaussInvYObs`, mu_, lambda_, lower_, upper_)
}

intInvGaussInvYLat <- function(mu_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intInvGaussInvYLat`, mu_, lambda_, lower_, upper_)
}

sumPoissonY <- function(mu, lower_, upper_) {
    .Call(`_LRMoECPNew_sumPoissonY`, mu, lower_, upper_)
}

sumPoissonYObs <- function(mu_, lower_, upper_) {
    .Call(`_LRMoECPNew_sumPoissonYObs`, mu_, lower_, upper_)
}

sumPoissonYLat <- function(mu_, lower_, upper_) {
    .Call(`_LRMoECPNew_sumPoissonYLat`, mu_, lower_, upper_)
}

intWeibullLogYObs <- function(k_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intWeibullLogYObs`, k_, lambda_, lower_, upper_)
}

intWeibullLogYLat <- function(k_, lambda_, lower_, upper_) {
    .Call(`_LRMoECPNew_intWeibullLogYLat`, k_, lambda_, lower_, upper_)
}

intWeibullPowYObs <- function(k_, lambda_, p_, lower_, upper_) {
    .Call(`_LRMoECPNew_intWeibullPowYObs`, k_, lambda_, p_, lower_, upper_)
}

intWeibullPowYLat <- function(k_, lambda_, p_, lower_, upper_) {
    .Call(`_LRMoECPNew_intWeibullPowYLat`, k_, lambda_, p_, lower_, upper_)
}

XAPlusYZB <- function(x, a, y, z, b) {
    .Call(`_LRMoECPNew_XAPlusYZB`, x, a, y, z, b)
}

XColMinusY <- function(x, y) {
    .Call(`_LRMoECPNew_XColMinusY`, x, y)
}

XPlusYColTimesZ <- function(x, y, z) {
    .Call(`_LRMoECPNew_XPlusYColTimesZ`, x, y, z)
}

XPlusYZ <- function(x, y, z) {
    .Call(`_LRMoECPNew_XPlusYZ`, x, y, z)
}

